# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pdf2raster.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(260, 230)
        MainWindow.setMinimumSize(QtCore.QSize(260, 230))
        MainWindow.setMaximumSize(QtCore.QSize(260, 230))
        font = QtGui.QFont()
        font.setKerning(True)
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 241, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.linePDF = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.linePDF.setObjectName("linePDF")
        self.horizontalLayout.addWidget(self.linePDF)
        self.btnOpen = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnOpen.setObjectName("btnOpen")
        self.horizontalLayout.addWidget(self.btnOpen)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineSave = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineSave.setObjectName("lineSave")
        self.horizontalLayout_2.addWidget(self.lineSave)
        self.btnSave = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_2.addWidget(self.btnSave)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.lineDPI = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineDPI.setObjectName("lineDPI")
        self.verticalLayout.addWidget(self.lineDPI)
        self.btnRun = QtWidgets.QPushButton(self.centralwidget)
        self.btnRun.setGeometry(QtCore.QRect(130, 132, 121, 51))
        self.btnRun.setObjectName("btnRun")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 120, 111, 61))
        self.groupBox.setObjectName("groupBox")
        self.rJPG = QtWidgets.QRadioButton(self.groupBox)
        self.rJPG.setGeometry(QtCore.QRect(10, 20, 89, 20))
        self.rJPG.setChecked(True)
        self.rJPG.setObjectName("rJPG")
        self.rTIFF = QtWidgets.QRadioButton(self.groupBox)
        self.rTIFF.setGeometry(QtCore.QRect(10, 40, 89, 20))
        self.rTIFF.setObjectName("rTIFF")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 260, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "pdf2raster"))
        self.linePDF.setPlaceholderText(_translate("MainWindow", "pliki pdf"))
        self.btnOpen.setText(_translate("MainWindow", "Otwórz"))
        self.lineSave.setPlaceholderText(_translate("MainWindow", "folder zapisu"))
        self.btnSave.setText(_translate("MainWindow", "Zapisz"))
        self.lineDPI.setPlaceholderText(_translate("MainWindow", "DPI"))
        self.btnRun.setText(_translate("MainWindow", "Konwertuj"))
        self.groupBox.setTitle(_translate("MainWindow", "Format"))
        self.rJPG.setText(_translate("MainWindow", "JPG"))
        self.rTIFF.setText(_translate("MainWindow", "TIFF"))
